=== Kawtherabd/Tour-Guide-Web-Application/XML/xsd/Ville.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!-- Élément racine : ville -->
    <xs:element name="ville">
        <xs:complexType>
            <xs:sequence>
                <!-- Élément descriptif -->
                <xs:element name="descriptif" type="xs:string"/>
                
                <!-- Élément sites -->
                <xs:element name="sites">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="site" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="nom" type="xs:string" use="required"/>
                                    <xs:attribute name="photo" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Élément hotels -->
                <xs:element name="hotels">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hotel" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Élément restaurants -->
                <xs:element name="restaurants">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="restaurant" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Élément gares -->
                <xs:element name="gares">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="gare" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Élément aéroports -->
                <xs:element name="aéroports">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="aéroport" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <!-- Attribut nom -->
            <xs:attribute name="nom" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Kawtherabd/Tour-Guide-Web-Application/XML/xml/Oran.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Ville.xsl"?>
<ville xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:noNamespaceSchemaLocation="xsd/Ville.xsd"  nom="Oran">

    <descriptif>Oran, située sur la côte nord-ouest de l'Algérie, est une ville portuaire 
    emblématique qui allie charme méditerranéen et richesse historique. Surnommée "La 
    Radieuse", elle est célèbre pour son architecture coloniale, ses places animées, et 
    ses plages pittoresques. Ville de musique et de culture, Oran est aussi connue comme le
     berceau du Raï, un genre musical algérien populaire. Les monuments tels que la 
     chapelle Santa Cruz et le fort de la Montagne Murja, ainsi que la splendeur de son 
     front de mer, en font une destination prisée pour les visiteurs et un trésor pour ses 
     habitants.</descriptif> 
    <sites> 
        <site nom="Santa Cruz" photo="images/SantaCruz.jpg"/>  
        <site nom="SidiElHouari" photo="images/SidiElHouari.jpg"/> 
    </sites> 
    <hotels> 
        <hotel>Royal Hotel</hotel> 
        <hotel>Le Méridien Oran</hotel> 
    </hotels> 
    <restaurants> 
        <restaurant>El Bahia</restaurant> 
        <restaurant>Le Corsaire</restaurant> 
    </restaurants> 
    <gares> 
        <gare>Oran Gare Centrale</gare> 
    </gares> 
    <aéroports> 
        <aéroport>Ahmed Ben Bella</aéroport> 
    </aéroports>  
</ville>

=== Kawtherabd/Tour-Guide-Web-Application/XML/xml/Londres.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/Ville.xsl"?>
<ville xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:noNamespaceSchemaLocation="xsd/Ville.xsd"  nom="Londres">

    <descriptif>Londres, capitale du Royaume-Uni, est une métropole mondiale et un centre
     historique, culturel et financier. Située sur les rives de la Tamise, cette ville 
     emblématique allie tradition et modernité, avec des monuments célèbres tels que le Big
      Ben, le Tower Bridge, et le Palais de Buckingham. Londres est également réputée pour 
      ses musées de classe mondiale, ses parcs verdoyants, ses quartiers animés comme Soho 
      et Camden, ainsi que ses marchés uniques. Elle offre une expérience culturelle et 
      touristique inégalée pour ses habitants et visiteurs.</descriptif> 
    <sites> 
        <site nom="Big Ben" photo="images/BigBen.jpg"/>  
        <site nom="Tower Bridge" photo="images/TowerBridge.jpg"/> 
    </sites> 
    <hotels> 
        <hotel>The Savoy</hotel> 
        <hotel>The Ritz London</hotel> 
    </hotels> 
    <restaurants> 
        <restaurant>Dishoom</restaurant> 
        <restaurant>Rules</restaurant> 
    </restaurants> 
    <gares> 
        <gare>London King's Cross</gare> 
        <gare>London Victoria</gare> 
    </gares> 
    <aéroports> 
        <aéroport>London Heathrow</aéroport> 
        <aéroport>London Gatwick</aéroport> 
    </aéroports>  
</ville>

=== Kawtherabd/Tour-Guide-Web-Application/XML/xml/Alger.xml
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="xsl/Ville.xsl"?>
<ville xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:noNamespaceSchemaLocation="xsd/Ville.xsd"  nom="Alger">

    <descriptif>Située au bord de la mer Méditerranée, Alger est une ville dynamique alliant 
    modernité et histoire. Capitale de l'Algérie, elle se distingue par son architecture 
    unique, mélangeant influences coloniales françaises et traditions arabes. La Casbah, son 
    vieux quartier inscrit au patrimoine mondial de l'UNESCO, regorge de ruelles étroites et 
    de monuments historiques, témoins d'un passé riche et mouvementé. Alger est aussi un 
    centre culturel et économique majeur, avec de nombreux musées, théâtres, et institutions 
    dédiées à la préservation de son patrimoine. Ses plages, son port animé, et ses restaurants 
    réputés en font une destination prisée des visiteurs, tout en étant un lieu de vie vibrant 
    pour ses habitants.</descriptif> 
    <sites> 
        <site nom="Casbah" photo="images/casbah.jpg"/>  
        <site nom="Bastion 23" photo="images/bastion23.jpg"/> 
    </sites> 
    <hotels> 
        <hotel>El Aurassi</hotel> 
        <hotel>El Djazair</hotel> 
    </hotels> 
    <restaurants> 
        <restaurant>El Nadjah</restaurant> 
        <restaurant>El Bena</restaurant> 
    </restaurants> 
    <gares> 
    <gare>Caroubier</gare> 
    </gares> 
    <aéroports> 
    <aéroport>Houari Boumediene</aéroport> 
    </aéroports>  
</ville>
